#!/usr/bin/env sh

echo "###########################################
WARNING! THIS IS LEGACY MODE!
DO NOT USE THIS IF YOU ARE A OKKCNC DEVELOPER
GO TO REPOSITORY ROOT AND LAUNCH OKKCNC USING
FOLLOWING COMMAND:

python3 -m OKKCNC
###########################################
"

DIR=`dirname $0`
PYTHONPATH=${DIR}:${DIR}/lib:${DIR}/plugins:${DIR}/controllers
export DIR PYTHONPATH

python3 ${DIR}/__main__.py $*
#python -m cProfile -o OKKCNC.out ${DIR}/__main__.py $*
